# Generated by Django 4.0.1 on 2022-01-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
