# Generated by Django 4.0.1 on 2022-01-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post1',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
