# Generated by Django 4.0.1 on 2022-01-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_post1_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descrption', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('genger', models.CharField(choices=[('Drama', 'Drama'), ('Horror', 'Horror'), ('Romantic', 'Romantic'), ('Anime', 'Anime')], max_length=100)),
                ('data_filmed', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post1',
        ),
    ]
