# Generated by Django 4.0.1 on 2022-01-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_rename_posts_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data_filmed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
