# Generated by Django 4.0.1 on 2022-01-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_data_filmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descrption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='genger',
            new_name='genre',
        ),
    ]
