# Generated by Django 4.0.1 on 2022-01-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_bookcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookExperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_expert', to='book.book')),
            ],
        ),
    ]
