# Generated by Django 4.0.1 on 2022-01-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_bookexperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('info_exp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpertRecomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendation', models.TextField()),
                ('expert_selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.expert')),
            ],
        ),
        migrations.DeleteModel(
            name='BookExperty',
        ),
    ]
