# Generated by Django 4.0.1 on 2022-01-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TWShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descrptions', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('quantity', models.IntegerField()),
                ('genger', models.CharField(choices=[('Drama', 'Drama'), ('Horror', 'Horror'), ('Romantic', 'Romantic'), ('Anime', 'Anime')], max_length=100)),
                ('data_filmed', models.DateField()),
            ],
        ),
    ]
